### ISSUE TITLE
What is the flow to predict the result of League

### ISSUE THREAD

**Issue by parthr-sib** [pbulsink/HockeyModel#2]
Hello @pbulsink 

I have successfully been able to load the project with all the dependencies. I have attached the screenshot for same. But now I don't know how to predict the result using this code. I am new to 'R' and it's concepts. So can you please help me with [this.](url
![r_model](https://user-images.githubusercontent.com/24225406/56960578-f1dedd00-6b6e-11e9-9039-338b2d44b46a.png)
)

**Comment by pbulsink** [comment]
I've written up some instructions for basic usage. It's beyond the scope of this project to teach R, there are many good hockey & R tutorials on the web, however some of the prediction code is outlined in the new vignette and in the earlier vignettes. See #6 and [https://github.com/pbulsink/HockeyModel/blob/master/vignettes/basic-usage.Rmd](https://github.com/pbulsink/HockeyModel/blob/master/vignettes/basic-usage.Rmd).
